### ISSUE TITLE
FE login dosn't work

### ISSUE THREAD

**Issue by andrea-86** [tschikarski/shibboleth#32]
The plugin work as expected. Redirect to idp page, import the user(if not exist on fe:user) but didn't make the login. Every time i try to go to the personal area shiobbolet redirect me to the IDP, that's see me just logged and redirect me to the home.

**Comment by tschikarski** [comment]
It is hard to guess what could go wrong from without more details, because there is a lot of configurations within the Service Provider and the Apache environment that can influence the behaviour. However, let's give it a try.

- Please check, if shibboleth was able to create a user in your FE user folder. 
- If that's the case, check that you have a FE user group and that the user is member of the group. (You have to create the group by yourself.)
- Please also check, if you put the page ID of the FE user and groups folder correctly into the extension configuration.

Please also note that you have to use https.

If that doesn't help, please make sure to look at the documentation, especially the checklists (https://service.trustcnct.net/shibboleth_doc/Configuration/Checklists/Index.html) and the debugging section (https://service.trustcnct.net/shibboleth_doc/Debugging/Index.html).

If my few hints do not help, you probably have to install the devlog extension and check the devlog after another login attempt. Use a filter to select entries from the extension. You should get detailed information about the sequence of events and the final outcome of the login attempt. The log will also contain the Apache environment at the time of returning from the IdP, which is essential for further debugging. Please note that you should deactivate devlog before using production data to avoid data leaks.

In any case, I would be happy to get another response from you to know the outcome.

**Comment by tschikarski** [comment]
As I got no response so far, I guess there is no further help needed?
